
<table class="table table-hover">
    <thead>
    <tr>
        <th>Grupo</th>
        <th>Materia</th>
        <th>Lunes</th>
        <th>Martes</th>
        <th>Miércoles</th>
        <th>Jueves</th>
        <th>Viernes</th>
    </tr>
    </thead>
    <tbody>
    @for($i=0;$i<count($horarios);$i++)
        <tr>
            <td>
                {{$horarios[$i]->nombre}}
            </td>
            <td>
                {{$horarios[$i]->salon}}
            </td>
            <td>
                {{$dias[$i]->dias->Lunes}}
            </td>
            <td>
                {{$dias[$i]->dias->Martes}}
            </td>
            <td>
                {{$dias[$i]->dias->Miercoles}}
            </td>
            <td>
                {{$dias[$i]->dias->Jueves}}
            </td>
            <td>
                {{$dias[$i]->dias->Viernes}}
            </td>

        </tr>
    @endfor
    </tbody>
</table>